SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS `ai_call_log` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT 'AI call log id',
  `request_id` varchar(64) NOT NULL COMMENT 'unique request id generated by ai-service',
  `biz_type` varchar(40) NOT NULL COMMENT 'CUSTOMER_SERVICE_RAG/OPERATIONS_REPORT/WORKORDER_ANALYZE',
  `biz_key` varchar(128) NULL DEFAULT NULL COMMENT 'business key, such as repair id or community id',
  `provider` varchar(40) NOT NULL COMMENT 'SPRING_AI_RAG/SPRING_AI_OPERATIONS/SPRING_AI/RULE fallback',
  `provider_version` varchar(64) NULL DEFAULT NULL COMMENT 'prompt/provider version',
  `model` varchar(100) NULL DEFAULT NULL COMMENT 'model name',
  `status` varchar(20) NOT NULL COMMENT 'SUCCESS/FALLBACK/FAILED',
  `latency_ms` int NULL DEFAULT NULL COMMENT 'request latency in milliseconds',
  `confidence` int NULL DEFAULT NULL COMMENT 'final normalized confidence',
  `request_summary` varchar(1000) NULL DEFAULT NULL COMMENT 'short request summary',
  `response_summary` varchar(1000) NULL DEFAULT NULL COMMENT 'short response summary',
  `retrieved_source_ids` varchar(1000) NULL DEFAULT NULL COMMENT 'RAG retrieved source ids',
  `error_message` varchar(2000) NULL DEFAULT NULL COMMENT 'failure or fallback reason',
  `create_time` datetime NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'create time',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uk_request_id` (`request_id`) USING BTREE,
  KEY `idx_biz_type_time` (`biz_type`, `create_time`) USING BTREE,
  KEY `idx_status_time` (`status`, `create_time`) USING BTREE,
  KEY `idx_provider_time` (`provider`, `create_time`) USING BTREE
) ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf8mb4
  COLLATE = utf8mb4_0900_ai_ci
  COMMENT = 'AI call observability log'
  ROW_FORMAT = DYNAMIC;
