CREATE TABLE IF NOT EXISTS `biz_work_order_ai_analysis` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'primary key',
  `repair_id` bigint(20) NOT NULL COMMENT 'related repair report id',
  `work_order_id` bigint(20) DEFAULT NULL COMMENT 'related work order id',
  `category` varchar(32) NOT NULL COMMENT 'AI category',
  `priority` tinyint(4) NOT NULL DEFAULT '1' COMMENT 'AI recommended priority, 1-4',
  `urgency_level` varchar(32) DEFAULT NULL COMMENT 'AI urgency level: LOW/MEDIUM/HIGH/CRITICAL',
  `risk_level` varchar(32) NOT NULL DEFAULT 'LOW' COMMENT 'LOW / MEDIUM / HIGH',
  `recommended_team` varchar(64) DEFAULT NULL COMMENT 'recommended maintenance team',
  `suggested_action` text COMMENT 'suggested handling action',
  `summary` varchar(255) DEFAULT NULL COMMENT 'AI summary',
  `extracted_location` varchar(255) DEFAULT NULL COMMENT 'AI extracted location supplement from repair text',
  `suggested_response_minutes` int DEFAULT NULL COMMENT 'AI suggested response time limit in minutes',
  `safety_tips` text COMMENT 'AI safety tips as JSON array text',
  `matched_keywords` varchar(512) DEFAULT NULL COMMENT 'comma separated matched keywords',
  `confidence` tinyint(4) DEFAULT NULL COMMENT 'confidence from 0 to 100',
  `manual_review_needed` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'whether staff should review before acting',
  `provider` varchar(32) NOT NULL DEFAULT 'RULE' COMMENT 'analysis provider source',
  `provider_version` varchar(64) DEFAULT NULL COMMENT 'provider version',
  `latest` tinyint(1) NOT NULL DEFAULT '1' COMMENT 'whether this is the latest snapshot for the repair report',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT 'created time',
  PRIMARY KEY (`id`),
  KEY `idx_repair_latest` (`repair_id`, `latest`),
  KEY `idx_work_order_id` (`work_order_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AI work order analysis snapshot';
